### ISSUE TITLE
Wrong import statement when generating files in a different directory than the file name

### ISSUE THREAD

**Issue by nicolas-martin** [micro/protoc-gen-micro#11]
I have the following structure
```
|____tools
| |____protos
| | |____prototool.yaml
| | |____serviceB
| | | |____b.proto
| | |____serviceA
| | | |____a.proto
```

b.proto
```proto
syntax = "proto3";

package b;

option go_package = "b";

message BarType {
    string Bar = 1;
}
```
a.proto
```proto
syntax = "proto3";

import "serviceB/b.proto";
package a;

option go_package = "a";

message HelloResponse {
    b.BarType bar = 1;
}
```

With an output dir of `../../pb`

My `a.micro.go` import is wrong
`import _ "github/pb/serviceB"`

while my `a.pb.go` is correct
`import serviceB "serviceB"`

**Comment by nicolas-martin** [comment]
Using https://github.com/uber/prototool

prototool.yml
```yml
protoc_version: 3.5.1

protoc_include_wkt: true

gen:
  go_options:
    import_path: github.com/test/pb

  plugins:
    - name:   go  
      flags:  plugins=grpc
      output: ../../pb
    - name:   micro
      type:   go
      output: ../../pb
```

`prototool gen`
